In [1]:
import tensorflow as tf
import numpy as np
import pandas as pd
import seaborn as sns
from pre_processing import *

In [5]:
product

,product_id,family_id,negocio_id,category_id,tier_id,utilidad_bruta_transf
0,881,1291,20,131,4,10.378017
1,805,1224,20,131,3,10.177925
2,892,1089,20,146,1,10.008243
3,841,1224,20,131,3,7.698362
4,830,1089,20,131,1,7.353678
...,...,...,...,...,...,...
932,786,1447,22,192,1,-0.184480
933,832,1447,22,192,3,-0.184480
934,848,1447,22,192,3,-0.184480
935,849,1447,22,192,2,-0.184480
936,933,1447,22,192,3,-0.184480

In [2]:
customers_products = tf.constant(matrix.copy())
num_customers = customers_products.shape[0]

In [ ]:
products_features =

In [ ]:
get_product_similarity()